root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  architecture/overview: architecture/overview.md
  implementation/state-management: implementation/state-management.md
  technical/merkle: technical/merkle.md 